#!/usr/bin/env ruby

require File.expand_path(File.dirname(__FILE__) + '/mdocker.rb')

mdocker_command = ARGV.size > 0 ? ARGV[0] : 'run'
case mdocker_command
  when 'run'
    user_command = ARGV.drop(1)
    if user_command.nil? or user_command.size == 0
      user_command = %w(/bin/bash -l)
    end
    begin
      exit MDocker.run(Dir.pwd, 'docker', user_command)
    rescue Exception => e
      STDERR.puts 'mdocker: ' + e.message
      exit 1
    end
  else
    STDERR.puts "mdocker: unknown command '#{mdocker_command}'"
    exit 1
end